title: Data-Centric Resources
description: A collection of data-centric resources for machine learning and natural language processing.
theme: just-the-docs

color_scheme: wider

url: https://www.stephanieschoch.com/data-centric-resources

heading_anchors: true
# aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Back to top link
back_to_top: false
back_to_top_text: "Back to top"

collections:
  papers:
    permalink: "/:collection/:path/"
    nav_fold: true
    output: true
  additional:
    permalink: "/:collection/:path/"
    nav_fold: true
    output: true

just_the_docs:
  collections:
    papers:
      name: Papers
    additional:
      name: Additional Resources


